# Generated by Django 5.0.7 on 2024-07-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
